mybatis:
  mapper-locations: mapper/*/*.xml
  type-aliases-package: com.litte.entity
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/litte
#    username: root
#    password: root
    url: jdbc:mysql://120.27.11.164:3306/litte
    username: estate
    password: estate123
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10Mb
mvc:
    view:
      suffix: .html
      prefix: /templates/


server:
  port: 80
logging:
  path: e:/log
  file: litte.log
  level:
    com.litte: debug









